# Generated by Django 2.1.1 on 2018-10-05 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('start', 'start'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='start', max_length=100)),
                ('status_info', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name_plural': 'dictionaries'},
        ),
        migrations.AddField(
            model_name='searchtermsfile',
            name='classification_file',
            field=models.FileField(blank=True, null=True, upload_to='classification_file/'),
        ),
        migrations.AddField(
            model_name='searchtermsfile',
            name='has_been_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingstatus',
            name='search_terms_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SearchTermsFile'),
        ),
    ]
