# Generated by Django 2.1.1 on 2018-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181005_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingstatus',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('start', 'start'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='new', max_length=100),
        ),
    ]
