# Generated by Django 2.1.1 on 2018-10-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181005_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('start', 'start'), ('processing', 'processing'), ('done', 'done'), ('error', 'error')], default='new', max_length=100)),
                ('status_info', models.CharField(blank=True, max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('search_terms_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SearchTermsFile', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='processingstatus',
            name='search_terms_file',
        ),
        migrations.DeleteModel(
            name='ProcessingStatus',
        ),
    ]
