# Generated by Django 2.1.1 on 2018-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181005_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtermsfile',
            name='classification_file',
            field=models.FilePathField(blank=True, null=True, path='/home/jakamkon/webapps/upwork_search_classification_static/media/classification_files'),
        ),
    ]
