# Generated by Django 2.1.1 on 2018-11-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181102_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255)),
                ('search_dictionary_ids', models.CharField(blank=True, max_length=255)),
                ('portfolio_ids', models.CharField(blank=True, max_length=255)),
                ('paid_impressions', models.IntegerField(blank=True)),
                ('paid_clicks', models.IntegerField(blank=True)),
                ('paid_cost', models.IntegerField(blank=True)),
                ('paid_conversions', models.FloatField(blank=True)),
                ('paid_total_conv', models.FloatField(blank=True)),
                ('organic_clicks', models.IntegerField(blank=True)),
                ('organic_impressions', models.IntegerField(blank=True)),
                ('organic_avg_position', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_classification',
            },
        ),
        migrations.CreateModel(
            name='SearchDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('attribute', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_dictionary',
            },
        ),
        migrations.CreateModel(
            name='SearchPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_portfolio',
            },
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255)),
                ('clicks', models.IntegerField(blank=True)),
                ('impressions', models.IntegerField(blank=True)),
                ('avg_position', models.FloatField(blank=True)),
                ('cost', models.IntegerField(blank=True)),
                ('conversions', models.FloatField(blank=True)),
                ('total_conv', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SearchPortfolio')),
            ],
            options={
                'db_table': 'search_term',
            },
        ),
    ]
