# Generated by Django 2.1.1 on 2018-11-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_searchclassification_searchdictionary_searchportfolio_searchterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchterm',
            name='avg_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='conversions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='impressions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='search_portfolio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.SearchPortfolio'),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='total_conv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
