# Generated by Django 2.1.1 on 2018-11-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181103_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
