# Generated by Django 2.1.3 on 2018-11-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181103_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclassification',
            name='organic_avg_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='organic_clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='organic_impressions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_conversions',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_impressions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchclassification',
            name='paid_total_conv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
