# Generated by Django 2.1.3 on 2018-11-05 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20181105_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.FloatField(blank=True, null=True)),
                ('partial', models.FloatField(blank=True, null=True)),
                ('unclassified', models.FloatField(blank=True, null=True)),
                ('search_portfolio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.SearchPortfolio')),
            ],
            options={
                'db_table': 'search_match',
            },
        ),
        migrations.CreateModel(
            name='SearchMatchTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.FloatField(blank=True, null=True)),
                ('partial', models.FloatField(blank=True, null=True)),
                ('unclassified', models.FloatField(blank=True, null=True)),
                ('unclassified_partial', models.IntegerField(blank=True, null=True)),
                ('partial_full', models.IntegerField(blank=True, null=True)),
                ('unclassified_full', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_match_total',
            },
        ),
    ]
