# Generated by Django 2.1.3 on 2018-11-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_searchmatch_searchmatchtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclassification',
            name='query',
            field=models.CharField(blank=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='query',
            field=models.CharField(blank=True, max_length=510),
        ),
    ]
