# Generated by Django 2.1.3 on 2018-11-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20181106_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclassification',
            name='search_dictionary_ids',
            field=models.CharField(blank=True, max_length=510),
        ),
    ]
